// ─── Owners ──────────────────────────────────────────────────────────────────
/*
export type Owner = {
  id: string;
  name: string;
  phone: string;
  email: string;
  city: string;
  verified: boolean;
  rating: number;
  totalProperties: number;
  bio: string;
  avatar: string;
};

export const OWNERS: Owner[] = [
  {
    id: "o1",
    name: "Ramesh Kapoor",
    phone: "+91 98110 34567",
    email: "ramesh.kapoor@gmail.com",
    city: "Delhi",
    verified: true,
    rating: 4.8,
    totalProperties: 5,
    bio: "Retired civil engineer with 20+ years of property management experience in South Delhi.",
    avatar: "https://i.pravatar.cc/150?img=70",
  },
  {
    id: "o2",
    name: "Surekha Iyer",
    phone: "+91 98204 56789",
    email: "surekha.iyer@yahoo.co.in",
    city: "Mumbai",
    verified: true,
    rating: 4.9,
    totalProperties: 8,
    bio: "Professional property manager handling premium flats in Andheri and Powai since 2008.",
    avatar: "https://i.pravatar.cc/150?img=23",
  },
  {
    id: "o3",
    name: "Narayana Swamy",
    phone: "+91 80931 22334",
    email: "narayana.swamy@outlook.com",
    city: "Bangalore",
    verified: true,
    rating: 4.7,
    totalProperties: 12,
    bio: "IT professional turned real-estate investor. All properties are professionally maintained.",
    avatar: "https://i.pravatar.cc/150?img=68",
  },
  {
    id: "o4",
    name: "Preethi Venkataraman",
    phone: "+91 94408 77890",
    email: "preethi.v@gmail.com",
    city: "Hyderabad",
    verified: true,
    rating: 4.6,
    totalProperties: 4,
    bio: "Interior designer who personally furnishes and maintains all rental units in Jubilee Hills.",
    avatar: "https://i.pravatar.cc/150?img=9",
  },
  {
    id: "o5",
    name: "Harish Malhotra",
    phone: "+91 98765 43210",
    email: "harish.malhotra@realtyindia.com",
    city: "Gurgaon",
    verified: true,
    rating: 4.5,
    totalProperties: 9,
    bio: "Director at Malhotra Realty. Specialises in premium co-living spaces in Gurgaon and Noida.",
    avatar: "https://i.pravatar.cc/150?img=52",
  },
  {
    id: "o6",
    name: "Anita Desai",
    phone: "+91 93222 67890",
    email: "anita.desai@gmail.com",
    city: "Pune",
    verified: false,
    rating: 4.3,
    totalProperties: 3,
    bio: "Independent landlord near FC Road and Hinjewadi offering student-friendly accommodation.",
    avatar: "https://i.pravatar.cc/150?img=25",
  },
  {
    id: "o7",
    name: "Sanjay Krishnamurthy",
    phone: "+91 99401 23456",
    email: "s.krishnamurthy@gmail.com",
    city: "Chennai",
    verified: true,
    rating: 4.7,
    totalProperties: 6,
    bio: "Chartered accountant managing family-owned heritage properties in Adyar and Besant Nagar.",
    avatar: "https://i.pravatar.cc/150?img=62",
  },
  {
    id: "o8",
    name: "Meghna Bose",
    phone: "+91 98310 11223",
    email: "meghna.bose@outlook.com",
    city: "Kolkata",
    verified: true,
    rating: 4.4,
    totalProperties: 3,
    bio: "Architect and property consultant managing modern flats in Salt Lake Sector V.",
    avatar: "https://i.pravatar.cc/150?img=44",
  },
];

// ─── Properties ───────────────────────────────────────────────────────────────

export type PropertyListing = {
  id: string;
  title: string;
  location: string;
  city: string;
  rent: number;
  propertyType: "apartment" | "villa" | "studio" | "house" | "pg";
  roomType: "private" | "shared" | "full";
  areaSqFt: number;
  amenities: string[];
  images: string[];
  ownerId: string;
  availableFrom: string;
  verified: boolean;
  rating: number;
  description: string;
  bedrooms: number;
  bathrooms: number;
};

export const PROPERTIES: PropertyListing[] = [
  {
    id: "p1",
    title: "Sunlit Studio in Whitefield",
    location: "Whitefield, Bangalore",
    city: "Bangalore",
    rent: 18000,
    propertyType: "studio",
    roomType: "full",
    areaSqFt: 450,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Furnished", "CCTV", "Lift", "Power Backup"],
    images: [
      "https://picsum.photos/seed/wb1/640/400",
      "https://picsum.photos/seed/wb2/640/400",
    ],
    ownerId: "o3",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.7,
    description: "Modern fully-furnished studio in the heart of Whitefield IT corridor. Walking distance to ITPL and major tech parks. Excellent connectivity via metro.",
  },
  {
    id: "p2",
    title: "Spacious 2BHK in Andheri West",
    location: "Andheri West, Mumbai",
    city: "Mumbai",
    rent: 45000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 900,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "AC", "Gym", "Swimming Pool", "Security", "Parking", "Lift"],
    images: [
      "https://picsum.photos/seed/maw1/640/400",
      "https://picsum.photos/seed/maw2/640/400",
    ],
    ownerId: "o2",
    availableFrom: "2026-04-15",
    verified: true,
    rating: 4.9,
    description: "Premium 2BHK in a gated society minutes from Versova beach and the Western Express Highway. Ideal for working professionals. Building has 24/7 security.",
  },
  {
    id: "p3",
    title: "Koramangala Co-living Flat",
    location: "6th Block, Koramangala, Bangalore",
    city: "Bangalore",
    rent: 25000,
    propertyType: "apartment",
    roomType: "private",
    areaSqFt: 700,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Laundry", "Housekeeping", "Kitchen", "AC", "TV"],
    images: [
      "https://picsum.photos/seed/bk1/640/400",
      "https://picsum.photos/seed/bk2/640/400",
    ],
    ownerId: "o3",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.6,
    description: "Private room in a well-managed co-living apartment. Koramangala 6th Block has the best cafes, startups, and nightlife in Bangalore. 2 km from Forum Mall.",
  },
  {
    id: "p4",
    title: "Connaught Place Serviced Suite",
    location: "Connaught Place, New Delhi",
    city: "Delhi",
    rent: 35000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 600,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Daily Housekeeping", "Room Service", "Parking", "Security"],
    images: [
      "https://picsum.photos/seed/dcp1/640/400",
      "https://picsum.photos/seed/dcp2/640/400",
    ],
    ownerId: "o1",
    availableFrom: "2026-04-20",
    verified: true,
    rating: 4.8,
    description: "Fully-serviced 1BHK in the commercial heart of New Delhi. Metro station within 200 m. Ideal for corporate professionals and consultants on extended stays.",
  },
  {
    id: "p5",
    title: "Powai Lake View 1BHK",
    location: "Powai, Mumbai",
    city: "Mumbai",
    rent: 32000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 750,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Lake View", "Gym", "Security", "Lift", "Parking"],
    images: [
      "https://picsum.photos/seed/mp1/640/400",
      "https://picsum.photos/seed/mp2/640/400",
    ],
    ownerId: "o2",
    availableFrom: "2026-05-15",
    verified: true,
    rating: 4.7,
    description: "Beautiful 1BHK overlooking Powai Lake. In the same complex as top tech offices. Hirananandani Gardens has some of Mumbai's best eateries and shopping.",
  },
  {
    id: "p6",
    title: "Banjara Hills Luxury Villa",
    location: "Road No. 12, Banjara Hills, Hyderabad",
    city: "Hyderabad",
    rent: 55000,
    propertyType: "villa",
    roomType: "full",
    areaSqFt: 2200,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["Wi-Fi", "Private Garden", "Swimming Pool", "Parking", "Generator", "CCTV"],
    images: [
      "https://picsum.photos/seed/hbh1/640/400",
      "https://picsum.photos/seed/hbh2/640/400",
    ],
    ownerId: "o4",
    availableFrom: "2026-06-01",
    verified: true,
    rating: 4.9,
    description: "Stunning 3BHK independent villa with private pool in the most premium address in Hyderabad. Walking distance to GVK One Mall and five-star hotels.",
  },
  {
    id: "p7",
    title: "Hadapsar IT Corridor Apartment",
    location: "Hadapsar, Pune",
    city: "Pune",
    rent: 16000,
    propertyType: "apartment",
    roomType: "shared",
    areaSqFt: 500,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Furnished", "Washing Machine", "Power Backup"],
    images: [
      "https://picsum.photos/seed/ph1/640/400",
      "https://picsum.photos/seed/ph2/640/400",
    ],
    ownerId: "o6",
    availableFrom: "2026-04-25",
    verified: false,
    rating: 4.2,
    description: "Affordable shared accommodation near Magarpatta IT Park and EON IT Park. Ideal for young professionals. Common areas kept clean. Strict no-smoking policy.",
  },
  {
    id: "p8",
    title: "Adyar Heritage Home",
    location: "Adyar, Chennai",
    city: "Chennai",
    rent: 22000,
    propertyType: "house",
    roomType: "private",
    areaSqFt: 800,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Terrace", "Garden", "Inverter", "Parking"],
    images: [
      "https://picsum.photos/seed/ca1/640/400",
      "https://picsum.photos/seed/ca2/640/400",
    ],
    ownerId: "o7",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.5,
    description: "Charming independent house in the tree-lined lanes of Adyar. Close to IIT Madras and Besant Nagar beach. Quiet and family-friendly neighbourhood.",
  },
  {
    id: "p9",
    title: "DLF Phase 2 Premium Flat",
    location: "DLF Phase 2, Gurgaon",
    city: "Gurgaon",
    rent: 28000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 1100,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Club House", "Gym", "Swimming Pool", "Security", "Parking", "Lift"],
    images: [
      "https://picsum.photos/seed/gd1/640/400",
      "https://picsum.photos/seed/gd2/640/400",
    ],
    ownerId: "o5",
    availableFrom: "2026-05-10",
    verified: true,
    rating: 4.6,
    description: "Premium 2BHK in DLF's most sought-after gated community. 10 minutes to Cyber City. Excellent metro connectivity via Sikanderpur station.",
  },
  {
    id: "p10",
    title: "Indiranagar 2BHK Retreat",
    location: "12th Main, Indiranagar, Bangalore",
    city: "Bangalore",
    rent: 30000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 950,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "AC", "Furnished", "Security", "Lift", "Balcony"],
    images: [
      "https://picsum.photos/seed/bi1/640/400",
      "https://picsum.photos/seed/bi2/640/400",
    ],
    ownerId: "o3",
    availableFrom: "2026-05-20",
    verified: true,
    rating: 4.8,
    description: "Elegant 2BHK in the heart of Indiranagar, Bangalore's most vibrant neighbourhood. Steps from 100 Feet Road. Surrounded by craft breweries, boutiques, and top eateries.",
  },
  {
    id: "p11",
    title: "Versova Beach House",
    location: "Versova, Andheri West, Mumbai",
    city: "Mumbai",
    rent: 65000,
    propertyType: "house",
    roomType: "full",
    areaSqFt: 1800,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["Wi-Fi", "Sea View", "Terrace", "Modular Kitchen", "Parking", "Security"],
    images: [
      "https://picsum.photos/seed/mv1/640/400",
      "https://picsum.photos/seed/mv2/640/400",
    ],
    ownerId: "o2",
    availableFrom: "2026-06-15",
    verified: true,
    rating: 4.9,
    description: "Spectacular 3BHK sea-facing bungalow in Versova fishermen's village. A rare find in Mumbai. The terrace offers panoramic Arabian Sea views. Creative professionals preferred.",
  },
  {
    id: "p12",
    title: "Jubilee Hills Luxury Apartment",
    location: "Jubilee Hills, Hyderabad",
    city: "Hyderabad",
    rent: 42000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 1400,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Wi-Fi", "AC", "Gym", "Club House", "Power Backup", "Security", "Parking"],
    images: [
      "https://picsum.photos/seed/hj1/640/400",
      "https://picsum.photos/seed/hj2/640/400",
    ],
    ownerId: "o4",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.7,
    description: "Spacious 3BHK in a premium high-rise overlooking Jubilee Hills. Minutes from Film Nagar and KBR National Park. Tastefully furnished with designer interiors.",
  },
  {
    id: "p13",
    title: "Lajpat Nagar Central Apartment",
    location: "Lajpat Nagar, South Delhi",
    city: "Delhi",
    rent: 20000,
    propertyType: "apartment",
    roomType: "private",
    areaSqFt: 600,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Inverter", "Parking", "Security"],
    images: [
      "https://picsum.photos/seed/dl1/640/400",
      "https://picsum.photos/seed/dl2/640/400",
    ],
    ownerId: "o1",
    availableFrom: "2026-04-15",
    verified: false,
    rating: 4.3,
    description: "Private room in a well-maintained flat near Lajpat Nagar Central Market. Metro station at 400 m. Great street food options. Ideal for working professionals.",
  },
  {
    id: "p14",
    title: "FC Road Student Housing",
    location: "Fergusson College Road, Pune",
    city: "Pune",
    rent: 12000,
    propertyType: "pg",
    roomType: "shared",
    areaSqFt: 350,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Meals Included", "Laundry", "Study Room", "CCTV"],
    images: [
      "https://picsum.photos/seed/pfc1/640/400",
      "https://picsum.photos/seed/pfc2/640/400",
    ],
    ownerId: "o6",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.4,
    description: "Affordable PG accommodation near Fergusson College and Deccan Gymkhana. Meals included. Ideal for students and fresh graduates. Warden on premises.",
  },
  {
    id: "p15",
    title: "Besant Nagar Beachside Flat",
    location: "Besant Nagar, Chennai",
    city: "Chennai",
    rent: 28000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 900,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Beach Access", "AC", "Lift", "Parking"],
    images: [
      "https://picsum.photos/seed/cb1/640/400",
      "https://picsum.photos/seed/cb2/640/400",
    ],
    ownerId: "o7",
    availableFrom: "2026-05-15",
    verified: true,
    rating: 4.8,
    description: "Rare 2BHK just two lanes from Besant Nagar beach. One of Chennai's most premium residential pockets. Modern interiors with sea breeze all year round.",
  },
  {
    id: "p16",
    title: "Marathahalli IT Hub Studio",
    location: "Marathahalli, Bangalore",
    city: "Bangalore",
    rent: 19000,
    propertyType: "studio",
    roomType: "full",
    areaSqFt: 480,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Furnished", "Power Backup", "Lift", "CCTV"],
    images: [
      "https://picsum.photos/seed/bm1/640/400",
      "https://picsum.photos/seed/bm2/640/400",
    ],
    ownerId: "o3",
    availableFrom: "2026-04-25",
    verified: true,
    rating: 4.5,
    description: "Compact furnished studio with fast Wi-Fi in Marathahalli, perfect for solo IT professionals. Close to Sakra World Hospital, Bagmane Tech Park, and Outer Ring Road.",
  },
  {
    id: "p17",
    title: "Salt Lake Sector V Tech Flat",
    location: "Sector V, Salt Lake, Kolkata",
    city: "Kolkata",
    rent: 15000,
    propertyType: "apartment",
    roomType: "shared",
    areaSqFt: 700,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Furnished", "Inverter", "Parking"],
    images: [
      "https://picsum.photos/seed/ksl1/640/400",
      "https://picsum.photos/seed/ksl2/640/400",
    ],
    ownerId: "o8",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.4,
    description: "Comfortable shared flat in Kolkata's IT hub Sector V. Close to Webel IT Park and Techno India campuses. Quiet building with professional co-tenants.",
  },
  {
    id: "p18",
    title: "HITEC City Premium Studio",
    location: "HITEC City, Hyderabad",
    city: "Hyderabad",
    rent: 21000,
    propertyType: "studio",
    roomType: "full",
    areaSqFt: 520,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Furnished", "Gym", "Security", "Lift"],
    images: [
      "https://picsum.photos/seed/hhc1/640/400",
      "https://picsum.photos/seed/hhc2/640/400",
    ],
    ownerId: "o4",
    availableFrom: "2026-05-05",
    verified: true,
    rating: 4.6,
    description: "Upscale furnished studio in HITEC City, Hyderabad's silicon valley. Walking distance to Microsoft, Google, and Amazon offices. Metro connectivity excellent.",
  },
];

// ─── Roommate Profiles ────────────────────────────────────────────────────────

export type RoommateProfile = {
  id: string;
  name: string;
  age: number;
  gender: "male" | "female";
  city: string;
  occupation: string;
  company: string;
  bio: string;
  compatibility: number;
  budget: number;
  lifestyle: {
    smoking: boolean;
    drinking: boolean;
    pets: boolean;
    schedule: "early_bird" | "night_owl" | "flexible";
    cleanliness: "high" | "medium" | "relaxed";
  };
  preferences: string[];
  preferredGender: "male" | "female" | "any";
  languages: string[];
  avatar: string;
  lookingIn: string[];
  propertyId?: string;
};

export const ROOMMATES: RoommateProfile[] = [
  {
    id: "r1",
    name: "Priya Sharma",
    age: 25,
    gender: "female",
    city: "Bangalore",
    occupation: "Software Engineer",
    company: "TCS",
    bio: "Calm and organised. I love early morning runs, home-cooked dal rice, and binge-reading on weekends. Looking for a clean, non-smoking flatmate in Koramangala.",
    compatibility: 96,
    budget: 18000,
    lifestyle: { smoking: false, drinking: false, pets: true, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Early Riser", "Pet Friendly", "Veg Kitchen", "Quiet Evenings"],
    preferredGender: "female",
    languages: ["Hindi", "English", "Punjabi"],
    avatar: "https://i.pravatar.cc/150?img=5",
    lookingIn: ["Koramangala", "Indiranagar", "HSR Layout"],
    propertyId: "p3",
  },
  {
    id: "r2",
    name: "Arjun Mehta",
    age: 27,
    gender: "male",
    city: "Mumbai",
    occupation: "Graphic Designer",
    company: "Ogilvy India",
    bio: "Creative night owl who keeps his space immaculate. Into jazz, Formula 1, and weekend treks. Looking for a chill flatmate who respects personal space.",
    compatibility: 94,
    budget: 22000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Night Owl", "Social Drinker", "Clean Kitchen"],
    preferredGender: "any",
    languages: ["Hindi", "English", "Gujarati"],
    avatar: "https://i.pravatar.cc/150?img=53",
    lookingIn: ["Andheri West", "Bandra", "Versova"],
    propertyId: "p2",
  },
  {
    id: "r3",
    name: "Kavya Reddy",
    age: 24,
    gender: "female",
    city: "Hyderabad",
    occupation: "Medical Intern",
    company: "Yashoda Hospitals",
    bio: "MBBS intern with irregular shifts. Very tidy, vegetarian, and absolutely no smoking. Love cooking Andhra food on weekends. Looking for a responsible flatmate.",
    compatibility: 91,
    budget: 12000,
    lifestyle: { smoking: false, drinking: false, pets: false, schedule: "flexible", cleanliness: "high" },
    preferences: ["Non-smoker", "Non-drinker", "Veg Kitchen", "Quiet Home"],
    preferredGender: "female",
    languages: ["Telugu", "Hindi", "English"],
    avatar: "https://i.pravatar.cc/150?img=10",
    lookingIn: ["Banjara Hills", "HITEC City", "Jubilee Hills"],
    propertyId: "p18",
  },
  {
    id: "r4",
    name: "Rahul Gupta",
    age: 28,
    gender: "male",
    city: "Pune",
    occupation: "Product Manager",
    company: "Infosys BPM",
    bio: "Startup enthusiast and amateur photographer. I work from home 3 days a week and need solid Wi-Fi. Very sociable but respect quiet hours post 11 PM.",
    compatibility: 89,
    budget: 15000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "flexible", cleanliness: "medium" },
    preferences: ["Non-smoker", "Work from Home", "Fast Wi-Fi", "Weekend Socials"],
    preferredGender: "any",
    languages: ["Hindi", "English", "Marathi"],
    avatar: "https://i.pravatar.cc/150?img=57",
    lookingIn: ["Koregaon Park", "Viman Nagar", "Kalyani Nagar"],
  },
  {
    id: "r5",
    name: "Sneha Nair",
    age: 26,
    gender: "female",
    city: "Bangalore",
    occupation: "Data Scientist",
    company: "Zoho Corporation",
    bio: "South Indian, fond of filter coffee and classical Carnatic music. I am quiet during the week and host friends occasionally on weekends. Looking for like-minded women.",
    compatibility: 93,
    budget: 20000,
    lifestyle: { smoking: false, drinking: false, pets: true, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Non-drinker", "Pet Friendly", "Classical Music OK"],
    preferredGender: "female",
    languages: ["Malayalam", "Tamil", "English", "Hindi"],
    avatar: "https://i.pravatar.cc/150?img=29",
    lookingIn: ["Indiranagar", "Domlur", "CV Raman Nagar"],
    propertyId: "p10",
  },
  {
    id: "r6",
    name: "Aditya Singh",
    age: 29,
    gender: "male",
    city: "Hyderabad",
    occupation: "Full Stack Developer",
    company: "Wipro Technologies",
    bio: "Tech guy who codes late, sleeps at 2 AM, and wakes at 10. Loves biryani, cricket, and Playstation. Need a chill flatmate who doesn't mind my schedule.",
    compatibility: 86,
    budget: 16000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Night Owl", "Gaming Friendly", "Flexible Schedule"],
    preferredGender: "male",
    languages: ["Hindi", "English", "Bhojpuri"],
    avatar: "https://i.pravatar.cc/150?img=64",
    lookingIn: ["HITEC City", "Gachibowli", "Kondapur"],
  },
  {
    id: "r7",
    name: "Ananya Krishnan",
    age: 23,
    gender: "female",
    city: "Bangalore",
    occupation: "MBA Student",
    company: "IIM Bangalore",
    bio: "First-year IIM student looking for accommodation near campus. Very studious during weekdays, but love exploring Bangalore's café scene on weekends.",
    compatibility: 88,
    budget: 14000,
    lifestyle: { smoking: false, drinking: false, pets: false, schedule: "flexible", cleanliness: "high" },
    preferences: ["Non-smoker", "Study-friendly", "Quiet Evenings", "Veg Preferred"],
    preferredGender: "female",
    languages: ["Tamil", "Kannada", "English", "Hindi"],
    avatar: "https://i.pravatar.cc/150?img=1",
    lookingIn: ["Bannerghatta Road", "JP Nagar", "Jayanagar"],
  },
  {
    id: "r8",
    name: "Vikram Patel",
    age: 30,
    gender: "male",
    city: "Ahmedabad",
    occupation: "Chartered Accountant",
    company: "KPMG India",
    bio: "Finance professional and weekend cyclist. Strictly vegetarian, non-alcoholic. Very particular about a clean home. Love cooking Gujarati food and sharing it.",
    compatibility: 82,
    budget: 12000,
    lifestyle: { smoking: false, drinking: false, pets: false, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Non-drinker", "Veg Kitchen", "Vegetarian", "Clean Home"],
    preferredGender: "male",
    languages: ["Gujarati", "Hindi", "English"],
    avatar: "https://i.pravatar.cc/150?img=50",
    lookingIn: ["Navrangpura", "Satellite", "Vastrapur"],
  },
  {
    id: "r9",
    name: "Deepika Iyer",
    age: 25,
    gender: "female",
    city: "Bangalore",
    occupation: "UX Designer",
    company: "Swiggy",
    bio: "UX designer obsessed with good design, street art, and craft beer. Work from Swiggy's Bangalore office 3 days a week. Looking for creative flatmates in vibrant areas.",
    compatibility: 95,
    budget: 22000,
    lifestyle: { smoking: false, drinking: true, pets: true, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Creative Types", "Pet Friendly", "Artsy Home"],
    preferredGender: "any",
    languages: ["Tamil", "Kannada", "English"],
    avatar: "https://i.pravatar.cc/150?img=33",
    lookingIn: ["Koramangala", "HSR Layout", "Indiranagar"],
    propertyId: "p3",
  },
  {
    id: "r10",
    name: "Rohit Kapoor",
    age: 27,
    gender: "male",
    city: "Delhi",
    occupation: "Marketing Manager",
    company: "Amazon India",
    bio: "Marketing manager who travels 10 days a month. Keep my room clean, pay rent on time, value privacy and respect. Looking for a professional flatmate in South Delhi.",
    compatibility: 90,
    budget: 20000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Professional", "Privacy Valued", "Clean Common Areas"],
    preferredGender: "any",
    languages: ["Hindi", "English", "Punjabi"],
    avatar: "https://i.pravatar.cc/150?img=51",
    lookingIn: ["Greater Kailash", "Lajpat Nagar", "South Extension"],
    propertyId: "p13",
  },
  {
    id: "r11",
    name: "Pooja Verma",
    age: 24,
    gender: "female",
    city: "Mumbai",
    occupation: "Fashion Designer",
    company: "Fab India",
    bio: "Textile designer who fills the home with fabric swatches and good music. Vegan, eco-conscious, and love indoor plants. Need a like-minded creative woman co-tenant.",
    compatibility: 87,
    budget: 18000,
    lifestyle: { smoking: false, drinking: false, pets: true, schedule: "flexible", cleanliness: "medium" },
    preferences: ["Non-smoker", "Vegan Kitchen", "Plants OK", "Creative", "Eco-friendly"],
    preferredGender: "female",
    languages: ["Hindi", "English"],
    avatar: "https://i.pravatar.cc/150?img=47",
    lookingIn: ["Bandra West", "Juhu", "Khar"],
  },
  {
    id: "r12",
    name: "Kiran Rao",
    age: 26,
    gender: "male",
    city: "Hyderabad",
    occupation: "AI Researcher",
    company: "CDAC Hyderabad",
    bio: "Deep into machine learning and philosophy. Introverted but friendly. I cook occasionally and keep shared spaces clean. Need fast internet and a quiet environment.",
    compatibility: 84,
    budget: 14000,
    lifestyle: { smoking: false, drinking: false, pets: false, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Non-drinker", "Fast Wi-Fi", "Quiet Home", "Bookish"],
    preferredGender: "any",
    languages: ["Kannada", "Telugu", "English", "Hindi"],
    avatar: "https://i.pravatar.cc/150?img=63",
    lookingIn: ["HITEC City", "Madhapur", "Gachibowli"],
    propertyId: "p18",
  },
  {
    id: "r13",
    name: "Meera Pillai",
    age: 28,
    gender: "female",
    city: "Chennai",
    occupation: "Senior Journalist",
    company: "The Hindu",
    bio: "Journalist with irregular hours (morning deadlines!). Love cooking Kerala food, reading, and Tamil cinema. Non-vegetarian, but respect all dietary preferences.",
    compatibility: 85,
    budget: 15000,
    lifestyle: { smoking: false, drinking: false, pets: true, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Pet Friendly", "Tidy Home", "Independent"],
    preferredGender: "female",
    languages: ["Malayalam", "Tamil", "English"],
    avatar: "https://i.pravatar.cc/150?img=41",
    lookingIn: ["Adyar", "Besant Nagar", "Thiruvanmiyur"],
    propertyId: "p15",
  },
  {
    id: "r14",
    name: "Siddharth Joshi",
    age: 25,
    gender: "male",
    city: "Pune",
    occupation: "Startup Founder",
    company: "Self-employed (SaaS)",
    bio: "Running a bootstrapped SaaS startup from home. Spend most of my day on calls. Need great Wi-Fi, quiet co-tenants, and an ergonomic-friendly flat. No drama.",
    compatibility: 88,
    budget: 18000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "flexible", cleanliness: "medium" },
    preferences: ["Non-smoker", "Work from Home", "Fast Wi-Fi", "Low Noise"],
    preferredGender: "any",
    languages: ["Marathi", "Hindi", "English"],
    avatar: "https://i.pravatar.cc/150?img=67",
    lookingIn: ["Koregaon Park", "Baner", "Aundh"],
  },
  {
    id: "r15",
    name: "Divya Agarwal",
    age: 23,
    gender: "female",
    city: "Delhi",
    occupation: "UPSC Aspirant",
    company: "Self-study",
    bio: "Full-time UPSC prep. I study 12 hours daily and need absolute quiet. Very clean, vegetarian, no smoking or drinking. Looking for a disciplined female co-tenant.",
    compatibility: 81,
    budget: 9000,
    lifestyle: { smoking: false, drinking: false, pets: false, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Non-drinker", "Vegetarian", "Silent Study Zone", "Female Only"],
    preferredGender: "female",
    languages: ["Hindi", "English"],
    avatar: "https://i.pravatar.cc/150?img=9",
    lookingIn: ["Mukherjee Nagar", "Karol Bagh", "Old Rajendra Nagar"],
  },
  {
    id: "r16",
    name: "Aryan Khanna",
    age: 26,
    gender: "male",
    city: "Noida",
    occupation: "Game Developer",
    company: "Ubisoft India",
    bio: "AAA game developer who sleeps late and plays guitar badly. My desk is chaotic but shared spaces are clean. Love cooking and feeding everyone. Very sociable.",
    compatibility: 83,
    budget: 16000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Night Owl", "Gaming Friendly", "Sociable"],
    preferredGender: "any",
    languages: ["Hindi", "English"],
    avatar: "https://i.pravatar.cc/150?img=68",
    lookingIn: ["Sector 62", "Sector 18", "Sector 50"],
  },
  {
    id: "r17",
    name: "Shreya Bose",
    age: 27,
    gender: "female",
    city: "Kolkata",
    occupation: "Architect",
    company: "Hafeez Contractor Studio",
    bio: "Architect who draws at midnight and drinks too much chai. Love classical Hindustani music, detective fiction, and Kolkata's Sunday morning book market.",
    compatibility: 92,
    budget: 12000,
    lifestyle: { smoking: false, drinking: false, pets: true, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Pet Friendly", "Artsy Home", "Books OK"],
    preferredGender: "female",
    languages: ["Bengali", "Hindi", "English"],
    avatar: "https://i.pravatar.cc/150?img=44",
    lookingIn: ["Salt Lake", "Park Street", "Alipore"],
    propertyId: "p17",
  },
  {
    id: "r18",
    name: "Tanmay Dey",
    age: 24,
    gender: "male",
    city: "Bangalore",
    occupation: "DevOps Engineer",
    company: "Google India",
    bio: "Googler who works hard and plays harder. Love trekking the Sahyadris on weekends. Non-smoker, occasional beer at home. Very punctual with rent and bills.",
    compatibility: 97,
    budget: 25000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Fitness Oriented", "Outdoors", "Punctual"],
    preferredGender: "any",
    languages: ["Bengali", "Hindi", "English", "Kannada"],
    avatar: "https://i.pravatar.cc/150?img=62",
    lookingIn: ["Whitefield", "Marathahalli", "Bellandur"],
    propertyId: "p1",
  },
];

// ─── Mock chat threads ────────────────────────────────────────────────────────

export type ChatContact = {
  id: string;
  name: string;
  avatar: string;
  lastMessage: string;
  time: string;
  unread: number;
  online: boolean;
  context: string; // what they're discussing
};

export type ChatMessage = {
  sender: "me" | "other";
  text: string;
  time: string;
};

export const CHAT_CONTACTS: ChatContact[] = [
  { id: "c1", name: "Priya Sharma", avatar: "https://i.pravatar.cc/150?img=5", lastMessage: "Yes, Koramangala works perfectly!", time: "2m", unread: 2, online: true, context: "Flat in Koramangala" },
  { id: "c2", name: "Arjun Mehta", avatar: "https://i.pravatar.cc/150?img=53", lastMessage: "Can we schedule a visit this Sunday?", time: "1h", unread: 0, online: false, context: "Andheri flat inquiry" },
  { id: "c3", name: "Narayana Swamy", avatar: "https://i.pravatar.cc/150?img=68", lastMessage: "Maintenance is covered in rent.", time: "3h", unread: 1, online: true, context: "Whitefield studio" },
  { id: "c4", name: "Kavya Reddy", avatar: "https://i.pravatar.cc/150?img=10", lastMessage: "I'm okay with the deposit amount.", time: "Yesterday", unread: 0, online: false, context: "HITEC City room" },
  { id: "c5", name: "Ramesh Kapoor", avatar: "https://i.pravatar.cc/150?img=70", lastMessage: "Lease is ready to be signed.", time: "Yesterday", unread: 0, online: false, context: "Lajpat Nagar flat" },
];

export const MOCK_THREADS: Record<string, ChatMessage[]> = {
  c1: [
    { sender: "other", text: "Hi! I saw your listing on Homigo for the 3BHK in Koramangala. Is the private room still available?", time: "10:02 AM" },
    { sender: "me", text: "Yes, it's available! The room is 14×12 ft with a built-in wardrobe and a dedicated work desk.", time: "10:05 AM" },
    { sender: "other", text: "Perfect. I'm a software engineer at TCS. I work standard hours and keep my space very clean. I prefer a non-smoking household.", time: "10:07 AM" },
    { sender: "me", text: "That matches our house rules exactly. No smoking, no parties on weekdays. We have two other flatmates — a designer and a data analyst.", time: "10:10 AM" },
    { sender: "other", text: "Sounds ideal. The rent is ₹25,000 right? Does that include maintenance and internet?", time: "10:12 AM" },
    { sender: "me", text: "Yes, ₹25,000 all-inclusive. 300 Mbps Wi-Fi, society maintenance, and housekeeping twice a week.", time: "10:14 AM" },
    { sender: "other", text: "Yes, Koramangala works perfectly!", time: "10:16 AM" },
  ],
  c2: [
    { sender: "other", text: "Hello! I'm interested in the 2BHK listing in Andheri West. I'm looking to move in by mid-April.", time: "9:00 AM" },
    { sender: "me", text: "Great! The flat is available from April 15. It's fully furnished with a modular kitchen and two ACs.", time: "9:15 AM" },
    { sender: "other", text: "That works. What's the security deposit? And is the building pet-free?", time: "9:20 AM" },
    { sender: "me", text: "Security deposit is 2 months (₹90,000). No pets allowed, sorry — building society rules.", time: "9:30 AM" },
    { sender: "other", text: "Understood. No pets is fine. Can we schedule a visit this Sunday?", time: "9:45 AM" },
  ],
  c3: [
    { sender: "other", text: "I am Narayana Swamy, the owner of the Whitefield studio. Thank you for your inquiry.", time: "2:00 PM" },
    { sender: "me", text: "Hi! Yes, I'm interested. Is the studio fully furnished?", time: "2:05 PM" },
    { sender: "other", text: "Yes, fully furnished with a queen bed, wardrobe, study table, and a modular kitchen. AC included.", time: "2:10 PM" },
    { sender: "me", text: "Great. What about maintenance and society charges?", time: "2:12 PM" },
    { sender: "other", text: "Maintenance is covered in rent. Society charges of ₹1,500/month are extra.", time: "2:15 PM" },
  ],
  c4: [
    { sender: "other", text: "Hi, I'm Kavya. I'm an MBBS intern at Yashoda Hospital. I'm interested in the room in HITEC City.", time: "11:00 AM" },
    { sender: "me", text: "Welcome Kavya! The room is in a women-only flat of three. Very safe area, 24/7 security in the building.", time: "11:10 AM" },
    { sender: "other", text: "That's reassuring. Is there a curfew? I sometimes have night shifts.", time: "11:15 AM" },
    { sender: "me", text: "No curfew at all. We all have professional lives so we understand irregular hours.", time: "11:20 AM" },
    { sender: "other", text: "I'm okay with the deposit amount.", time: "11:25 AM" },
  ],
  c5: [
    { sender: "other", text: "Namaste, I'm Ramesh Kapoor. I see you've applied for the Lajpat Nagar flat.", time: "4:00 PM" },
    { sender: "me", text: "Yes! I'm very interested. I've been looking in South Delhi for a while.", time: "4:05 PM" },
    { sender: "other", text: "Your profile looks good. Can you share your last 3 months' pay slips and employment letter?", time: "4:10 PM" },
    { sender: "me", text: "Of course, I'll send them right away on email.", time: "4:12 PM" },
    { sender: "other", text: "Lease is ready to be signed.", time: "4:30 PM" },
  ],
};*/
export type Owner = {
  id: string;
  name: string;
  phone: string;
  email: string;
  city: string;
  verified: boolean;
  rating: number;
  totalProperties: number;
  bio: string;
  avatar: string;
};

export const OWNERS: Owner[] = [
  {
    id: "o1",
    name: "Ramesh Kapoor",
    phone: "+91 98110 34567",
    email: "ramesh.kapoor@gmail.com",
    city: "Delhi",
    verified: true,
    rating: 4.8,
    totalProperties: 5,
    bio: "Retired civil engineer with 20+ years of property management experience in South Delhi.",
    avatar: "https://img.freepik.com/premium-photo/man-suit-stands-front-window_662214-545818.jpg",
  },
  {
    id: "o2",
    name: "Surekha Iyer",
    phone: "+91 98204 56789",
    email: "surekha.iyer@yahoo.co.in",
    city: "Mumbai",
    verified: true,
    rating: 4.9,
    totalProperties: 8,
    bio: "Professional property manager handling premium flats in Andheri and Powai since 2008.",
    avatar: "https://tse4.mm.bing.net/th/id/OIP._IigVNqyh782sCXCt2MZpgHaE7?cb=thfc1&w=626&h=417&rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    id: "o3",
    name: "Narayana Swamy",
    phone: "+91 80931 22334",
    email: "narayana.swamy@outlook.com",
    city: "Bangalore",
    verified: true,
    rating: 4.7,
    totalProperties: 12,
    bio: "IT professional turned real-estate investor. All properties are professionally maintained.",
    avatar: "https://tse2.mm.bing.net/th/id/OIP._rEusoWjUtIDuL3CEMFayAHaE7?cb=thfc1&w=626&h=417&rs=1&pid=ImgDetMain&o=7&rm=3",
  },
  {
    id: "o4",
    name: "Preethi Venkataraman",
    phone: "+91 94408 77890",
    email: "preethi.v@gmail.com",
    city: "Hyderabad",
    verified: true,
    rating: 4.6,
    totalProperties: 4,
    bio: "Interior designer who personally furnishes and maintains all rental units in Jubilee Hills.",
    avatar: "https://img.freepik.com/premium-photo/portrait-smiling-business-woman-office_449849-30302.jpg",
  },
  {
    id: "o5",
    name: "Harish Malhotra",
    phone: "+91 98765 43210",
    email: "harish.malhotra@realtyindia.com",
    city: "Gurgaon",
    verified: true,
    rating: 4.5,
    totalProperties: 9,
    bio: "Director at Malhotra Realty. Specialises in premium co-living spaces in Gurgaon and Noida.",
    avatar: "https://img.freepik.com/premium-photo/headshot-indian-businessman-formal-suit-smiling-confidently-office-background-indian-businessman-formal-suit_936686-26457.jpg?w=996",
  },
  {
    id: "o6",
    name: "Anita Desai",
    phone: "+91 93222 67890",
    email: "anita.desai@gmail.com",
    city: "Pune",
    verified: false,
    rating: 4.3,
    totalProperties: 3,
    bio: "Independent landlord near FC Road and Hinjewadi offering student-friendly accommodation.",
    avatar: "https://img.freepik.com/premium-photo/confident-ambitious-young-indian-woman-corporate-office_753390-7294.jpg",
  },
  {
    id: "o7",
    name: "Sanjay Krishnamurthy",
    phone: "+91 99401 23456",
    email: "s.krishnamurthy@gmail.com",
    city: "Chennai",
    verified: true,
    rating: 4.7,
    totalProperties: 6,
    bio: "Chartered accountant managing family-owned heritage properties in Adyar and Besant Nagar.",
    avatar: "https://img.freepik.com/premium-photo/indian-young-business-people-corporate-office-employees-concept_1257902-600.jpg",
  },
  {
    id: "o8",
    name: "Meghna Bose",
    phone: "+91 98310 11223",
    email: "meghna.bose@outlook.com",
    city: "Kolkata",
    verified: true,
    rating: 4.4,
    totalProperties: 3,
    bio: "Architect and property consultant managing modern flats in Salt Lake Sector V.",
    avatar: "https://img.freepik.com/premium-photo/confident-professional-woman-business-suit-smiling-camera_866475-1602.jpg",
  },
];

// ─── Properties ───────────────────────────────────────────────────────────────

export type PropertyListing = {
  id: string;
  title: string;
  location: string;
  city: string;
  rent: number;
  propertyType: "apartment" | "villa" | "studio" | "house" | "pg";
  roomType: "private" | "shared" | "full";
  areaSqFt: number;
  amenities: string[];
  images: string[];
  ownerId: string;
  availableFrom: string;
  verified: boolean;
  rating: number;
  description: string;
  bedrooms: number;
  bathrooms: number;
};

export const PROPERTIES: PropertyListing[] = [
  {
    id: "p1",
    title: "Sunlit Studio in Whitefield",
    location: "Whitefield, Bangalore",
    city: "Bangalore",
    rent: 18000,
    propertyType: "studio",
    roomType: "full",
    areaSqFt: 450,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Furnished", "CCTV", "Lift", "Power Backup"],
    images: [
      "https://images.nobroker.in/images/8a9fab8479c5f15f0179c64324da2b6f/8a9fab8479c5f15f0179c64324da2b6f_605895_998452_medium.jpg",
      "https://images.nobroker.in/images/8a9faf8494cd92db0194cf75d82336a7/8a9faf8494cd92db0194cf75d82336a7_61797_324507_medium.jpg",
    ],
    ownerId: "o3",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.7,
    description: "Modern fully-furnished studio in the heart of Whitefield IT corridor. Walking distance to ITPL and major tech parks. Excellent connectivity via metro.",
  },
  {
    id: "p2",
    title: "Spacious 2BHK in Andheri West",
    location: "Andheri West, Mumbai",
    city: "Mumbai",
    rent: 45000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 900,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "AC", "Gym", "Swimming Pool", "Security", "Parking", "Lift"],
    images: [
      "https://cdn.homedsgn.com/wp-content/uploads/2015/06/The-Bandra-House-27-1150x942.jpg",
      "https://cdn.homedsgn.com/wp-content/uploads/2015/06/The-Bandra-House-26.jpg",
    ],
    ownerId: "o2",
    availableFrom: "2026-04-15",
    verified: true,
    rating: 4.9,
    description: "Premium 2BHK in a gated society minutes from Versova beach and the Western Express Highway. Ideal for working professionals. Building has 24/7 security.",
  },
  {
    id: "p3",
    title: "Koramangala Co-living Flat",
    location: "6th Block, Koramangala, Bangalore",
    city: "Bangalore",
    rent: 25000,
    propertyType: "apartment",
    roomType: "private",
    areaSqFt: 700,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Laundry", "Housekeeping", "Kitchen", "AC", "TV"],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/15/97/e8/28/room.jpg?w=500&h=-1&s=1",
      "https://i.pinimg.com/736x/64/51/26/64512635506d354d9fefc8a146a6d0d1.jpg",
    ],
    ownerId: "o3",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.6,
    description: "Private room in a well-managed co-living apartment. Koramangala 6th Block has the best cafes, startups, and nightlife in Bangalore. 2 km from Forum Mall.",
  },
  {
    id: "p4",
    title: "Connaught Place Serviced Suite",
    location: "Connaught Place, New Delhi",
    city: "Delhi",
    rent: 35000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 600,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Daily Housekeeping", "Room Service", "Parking", "Security"],
    images: [
      "https://media-cdn.tripadvisor.com/media/photo-s/10/e2/96/01/treebo-fort-club.jpg",
      "https://media-cdn.tripadvisor.com/media/photo-s/0f/27/5d/a9/treebo-jai-ambe-maa.jpg",
    ],
    ownerId: "o1",
    availableFrom: "2026-04-20",
    verified: true,
    rating: 4.8,
    description: "Fully-serviced 1BHK in the commercial heart of New Delhi. Metro station within 200 m. Ideal for corporate professionals and consultants on extended stays.",
  },
  {
    id: "p5",
    title: "Powai Lake View 1BHK",
    location: "Powai, Mumbai",
    city: "Mumbai",
    rent: 32000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 750,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Lake View", "Gym", "Security", "Lift", "Parking"],
    images: [
      "https://images.nobroker.in/images/8a9f8f0392f0d6520192f140a02e2056/8a9f8f0392f0d6520192f140a02e2056_94463_996447_medium.jpg",
      "https://images.nobroker.in/images/8a9f8195709bbdee01709f8189bb6464/8a9f8195709bbdee01709f8189bb6464_36866_315754_medium.jpg",
    ],
    ownerId: "o2",
    availableFrom: "2026-05-15",
    verified: true,
    rating: 4.7,
    description: "Beautiful 1BHK overlooking Powai Lake. In the same complex as top tech offices. Hirananandani Gardens has some of Mumbai's best eateries and shopping.",
  },
  {
    id: "p6",
    title: "Banjara Hills Luxury Villa",
    location: "Road No. 12, Banjara Hills, Hyderabad",
    city: "Hyderabad",
    rent: 55000,
    propertyType: "villa",
    roomType: "full",
    areaSqFt: 2200,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["Wi-Fi", "Private Garden", "Swimming Pool", "Parking", "Generator", "CCTV"],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/14/3e/37/bf/amritsar-international.jpg?w=700&h=-1&s=1",
      "https://rainbow-international.hyderabad-hotel.com/data/Photos/OriginalPhoto/7356/735675/735675226/hyderabad-hotel-rainbow-international-photo-14.JPEG",
    ],
    ownerId: "o4",
    availableFrom: "2026-06-01",
    verified: true,
    rating: 4.9,
    description: "Stunning 3BHK independent villa with private pool in the most premium address in Hyderabad. Walking distance to GVK One Mall and five-star hotels.",
  },
  {
    id: "p7",
    title: "Hadapsar IT Corridor Apartment",
    location: "Hadapsar, Pune",
    city: "Pune",
    rent: 16000,
    propertyType: "apartment",
    roomType: "shared",
    areaSqFt: 500,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Furnished", "Washing Machine", "Power Backup"],
    images: [
      "https://images.nobroker.in/images/8a9f8a438fc32a72018fc34c96781165/8a9f8a438fc32a72018fc34c96781165_678166_181255_medium.jpg",
      "https://tse4.mm.bing.net/th/id/OIP.AMV-mJNUp5k2RKuQd-MzkAHaEK?cb=thfc1&pid=ImgDet&w=474&h=266&rs=1&o=7&rm=3",
    ],
    ownerId: "o6",
    availableFrom: "2026-04-25",
    verified: false,
    rating: 4.2,
    description: "Affordable shared accommodation near Magarpatta IT Park and EON IT Park. Ideal for young professionals. Common areas kept clean. Strict no-smoking policy.",
  },
  {
    id: "p8",
    title: "Adyar Heritage Home",
    location: "Adyar, Chennai",
    city: "Chennai",
    rent: 22000,
    propertyType: "house",
    roomType: "private",
    areaSqFt: 800,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Terrace", "Garden", "Inverter", "Parking"],
    images: [
      "https://images.nobroker.in/images/8a9f85039209f42901920a0fb5e8071a/8a9f85039209f42901920a0fb5e8071a_62538_463679_medium.jpg",
      "https://images.nobroker.in/images/8a9f8e8394fd438a0194fd9ac94711ff/8a9f8e8394fd438a0194fd9ac94711ff_435440_454917_medium.jpg",
    ],
    ownerId: "o7",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.5,
    description: "Charming independent house in the tree-lined lanes of Adyar. Close to IIT Madras and Besant Nagar beach. Quiet and family-friendly neighbourhood.",
  },
  {
    id: "p9",
    title: "DLF Phase 2 Premium Flat",
    location: "DLF Phase 2, Gurgaon",
    city: "Gurgaon",
    rent: 28000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 1100,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Club House", "Gym", "Swimming Pool", "Security", "Parking", "Lift"],
    images: [
      "https://images.nobroker.in/images/8a9fdb83898319d901898353c3871c8c/8a9fdb83898319d901898353c3871c8c_35495_161017_medium.jpg",
      "https://images.nobroker.in/images/ff808181559b4bf601559b54d7f3007b/ff808181559b4bf601559b54d7f3007b_60490_419557_medium.jpg",
    ],
    ownerId: "o5",
    availableFrom: "2026-05-10",
    verified: true,
    rating: 4.6,
    description: "Premium 2BHK in DLF's most sought-after gated community. 10 minutes to Cyber City. Excellent metro connectivity via Sikanderpur station.",
  },
  {
    id: "p10",
    title: "Indiranagar 2BHK Retreat",
    location: "12th Main, Indiranagar, Bangalore",
    city: "Bangalore",
    rent: 30000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 950,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "AC", "Furnished", "Security", "Lift", "Balcony"],
    images: [
      "https://media-cdn.tripadvisor.com/media/photo-s/06/cd/db/58/haku-service-apartments.jpg",
      "https://media-cdn.tripadvisor.com/media/photo-s/14/d0/49/0c/oyo-2282-apartment-velachery.jpg",
    ],
    ownerId: "o3",
    availableFrom: "2026-05-20",
    verified: true,
    rating: 4.8,
    description: "Elegant 2BHK in the heart of Indiranagar, Bangalore's most vibrant neighbourhood. Steps from 100 Feet Road. Surrounded by craft breweries, boutiques, and top eateries.",
  },
  {
    id: "p11",
    title: "Versova Beach House",
    location: "Versova, Andheri West, Mumbai",
    city: "Mumbai",
    rent: 65000,
    propertyType: "house",
    roomType: "full",
    areaSqFt: 1800,
    bedrooms: 3,
    bathrooms: 3,
    amenities: ["Wi-Fi", "Sea View", "Terrace", "Modular Kitchen", "Parking", "Security"],
    images: [
      "https://media-cdn.tripadvisor.com/media/photo-s/15/70/44/9e/oyo-9818-hotel-diamond.jpg",
      "https://r1imghtlak.mmtcdn.com/716f0caec3b611e8b8cc023b42bcea16.jpg?&downsize=573:*&crop=573:240;0,71&output-format=jpg",
    ],
    ownerId: "o2",
    availableFrom: "2026-06-15",
    verified: true,
    rating: 4.9,
    description: "Spectacular 3BHK sea-facing bungalow in Versova fishermen's village. A rare find in Mumbai. The terrace offers panoramic Arabian Sea views. Creative professionals preferred.",
  },
  {
    id: "p12",
    title: "Jubilee Hills Luxury Apartment",
    location: "Jubilee Hills, Hyderabad",
    city: "Hyderabad",
    rent: 42000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 1400,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Wi-Fi", "AC", "Gym", "Club House", "Power Backup", "Security", "Parking"],
    images: [
      "https://yatradham.org/media/catalog/product/i/m/img_4763.jpg",
      "https://cdn.yatradham.org/media/catalog/product/i/m/img_2960_1.jpg",
    ],
    ownerId: "o4",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.7,
    description: "Spacious 3BHK in a premium high-rise overlooking Jubilee Hills. Minutes from Film Nagar and KBR National Park. Tastefully furnished with designer interiors.",
  },
  {
    id: "p13",
    title: "Lajpat Nagar Central Apartment",
    location: "Lajpat Nagar, South Delhi",
    city: "Delhi",
    rent: 20000,
    propertyType: "apartment",
    roomType: "private",
    areaSqFt: 600,
    bedrooms: 3,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Inverter", "Parking", "Security"],
    images: [
      "https://images.nobroker.in/images/8a9f8a039057a71b019057ffe2171699/8a9f8a039057a71b019057ffe2171699_87630_702922_medium.jpg",
      "https://images.nobroker.in/images/8a9f990390904c7f0190905f572601dc/8a9f990390904c7f0190905f572601dc_24615_192821_medium.jpg",
    ],
    ownerId: "o1",
    availableFrom: "2026-04-15",
    verified: false,
    rating: 4.3,
    description: "Private room in a well-maintained flat near Lajpat Nagar Central Market. Metro station at 400 m. Great street food options. Ideal for working professionals.",
  },
  {
    id: "p14",
    title: "FC Road Student Housing",
    location: "Fergusson College Road, Pune",
    city: "Pune",
    rent: 12000,
    propertyType: "pg",
    roomType: "shared",
    areaSqFt: 350,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "Meals Included", "Laundry", "Study Room", "CCTV"],
    images: [
      "https://images.nobroker.in/images/8a9f84838fa820a7018fa86197350723/8a9f84838fa820a7018fa86197350723_2442_914303_medium.jpg",
      "https://images.nobroker.in/images/8a9f990390904c7f0190905f572601dc/8a9f990390904c7f0190905f572601dc_24615_192821_medium.jpg",
    ],
    ownerId: "o6",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.4,
    description: "Affordable PG accommodation near Fergusson College and Deccan Gymkhana. Meals included. Ideal for students and fresh graduates. Warden on premises.",
  },
  {
    id: "p15",
    title: "Besant Nagar Beachside Flat",
    location: "Besant Nagar, Chennai",
    city: "Chennai",
    rent: 28000,
    propertyType: "apartment",
    roomType: "full",
    areaSqFt: 900,
    bedrooms: 2,
    bathrooms: 2,
    amenities: ["Wi-Fi", "Beach Access", "AC", "Lift", "Parking"],
    images: [
      "https://images.nobroker.in/images/8a9f8503909be2aa01909c4c2bd423e9/8a9f8503909be2aa01909c4c2bd423e9_63098_403160_medium.jpg",
      "https://images.nobroker.in/images/8a9f930391bb6af10191bb9637300d67/8a9f930391bb6af10191bb9637300d67_17675_625044_medium.jpg",
    ],
    ownerId: "o7",
    availableFrom: "2026-05-15",
    verified: true,
    rating: 4.8,
    description: "Rare 2BHK just two lanes from Besant Nagar beach. One of Chennai's most premium residential pockets. Modern interiors with sea breeze all year round.",
  },
  {
    id: "p16",
    title: "Marathahalli IT Hub Studio",
    location: "Marathahalli, Bangalore",
    city: "Bangalore",
    rent: 19000,
    propertyType: "studio",
    roomType: "full",
    areaSqFt: 480,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Furnished", "Power Backup", "Lift", "CCTV"],
    images: [
      "https://images.nobroker.in/images/8a9f92ca7888301801788837f6c2023f/8a9f92ca7888301801788837f6c2023f_7274_988566_medium.jpg",
      "https://images.nobroker.in/images/8a9f931874aad36b0174abd7239d6a47/8a9f931874aad36b0174abd7239d6a47_1500_114371_medium.jpg",
    ],
    ownerId: "o3",
    availableFrom: "2026-04-25",
    verified: true,
    rating: 4.5,
    description: "Compact furnished studio with fast Wi-Fi in Marathahalli, perfect for solo IT professionals. Close to Sakra World Hospital, Bagmane Tech Park, and Outer Ring Road.",
  },
  {
    id: "p17",
    title: "Salt Lake Sector V Tech Flat",
    location: "Sector V, Salt Lake, Kolkata",
    city: "Kolkata",
    rent: 15000,
    propertyType: "apartment",
    roomType: "shared",
    areaSqFt: 700,
    bedrooms: 2,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Furnished", "Inverter", "Parking"],
    images: [
      "https://3.imimg.com/data3/NN/NN/GLADMIN-2535677/location_image-500x500.jpg",
      "https://tse2.mm.bing.net/th/id/OIP.dkdx5Hxej_7cBU1Wm64T1AHaE_?cb=thfc1&w=5333&h=3597&rs=1&pid=ImgDetMain&o=7&rm=3",
    ],
    ownerId: "o8",
    availableFrom: "2026-05-01",
    verified: true,
    rating: 4.4,
    description: "Comfortable shared flat in Kolkata's IT hub Sector V. Close to Webel IT Park and Techno India campuses. Quiet building with professional co-tenants.",
  },
  {
    id: "p18",
    title: "HITEC City Premium Studio",
    location: "HITEC City, Hyderabad",
    city: "Hyderabad",
    rent: 21000,
    propertyType: "studio",
    roomType: "full",
    areaSqFt: 520,
    bedrooms: 1,
    bathrooms: 1,
    amenities: ["Wi-Fi", "AC", "Furnished", "Gym", "Security", "Lift"],
    images: [
      "https://dynamic-media-cdn.tripadvisor.com/media/photo-o/1c/8f/58/89/family-4-bed-room-ac.jpg?w=700&h=-1&s=1",
      "https://tse4.mm.bing.net/th/id/OIP.9LDzCBSm0-Ep8tccSg0TrwHaEH?cb=thfc1&pid=ImgDet&w=474&h=263&rs=1&o=7&rm=3",
    ],
    ownerId: "o4",
    availableFrom: "2026-05-05",
    verified: true,
    rating: 4.6,
    description: "Upscale furnished studio in HITEC City, Hyderabad's silicon valley. Walking distance to Microsoft, Google, and Amazon offices. Metro connectivity excellent.",
  },
];

// ─── Roommate Profiles ────────────────────────────────────────────────────────

export type RoommateProfile = {
  id: string;
  name: string;
  age: number;
  gender: "male" | "female";
  city: string;
  occupation: string;
  company: string;
  bio: string;
  compatibility: number;
  budget: number;
  lifestyle: {
    smoking: boolean;
    drinking: boolean;
    pets: boolean;
    schedule: "early_bird" | "night_owl" | "flexible";
    cleanliness: "high" | "medium" | "relaxed";
  };
  preferences: string[];
  preferredGender: "male" | "female" | "any";
  languages: string[];
  avatar: string;
  lookingIn: string[];
  propertyId?: string;
};

export const ROOMMATES: RoommateProfile[] = [
  {
    id: "r1",
    name: "Priya Sharma",
    age: 25,
    gender: "female",
    city: "Bangalore",
    occupation: "Software Engineer",
    company: "TCS",
    bio: "Calm and organised. I love early morning runs, home-cooked dal rice, and binge-reading on weekends. Looking for a clean, non-smoking flatmate in Koramangala.",
    compatibility: 96,
    budget: 18000,
    lifestyle: { smoking: false, drinking: false, pets: true, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Early Riser", "Pet Friendly", "Veg Kitchen", "Quiet Evenings"],
    preferredGender: "female",
    languages: ["Hindi", "English", "Punjabi"],
    avatar: "https://img.freepik.com/premium-photo/young-smart-indian-businesswoman-smiling-face-standing-blur-background-modern-office-building-generative-ai-aig20_31965-130044.jpg",
    lookingIn: ["Koramangala", "Indiranagar", "HSR Layout"],
    propertyId: "p3",
  },
  {
    id: "r2",
    name: "Arjun Mehta",
    age: 27,
    gender: "male",
    city: "Mumbai",
    occupation: "Graphic Designer",
    company: "Ogilvy India",
    bio: "Creative night owl who keeps his space immaculate. Into jazz, Formula 1, and weekend treks. Looking for a chill flatmate who respects personal space.",
    compatibility: 94,
    budget: 22000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Night Owl", "Social Drinker", "Clean Kitchen"],
    preferredGender: "any",
    languages: ["Hindi", "English", "Gujarati"],
    avatar: "https://img.freepik.com/premium-photo/young-smart-indian-businessman-smiling-face-standing-blur-background-busy-office-generative-ai-aig20_31965-142159.jpg",
    lookingIn: ["Andheri West", "Bandra", "Versova"],
    propertyId: "p2",
  },
  {
    id: "r3",
    name: "Kavya Reddy",
    age: 24,
    gender: "female",
    city: "Hyderabad",
    occupation: "Medical Intern",
    company: "Yashoda Hospitals",
    bio: "MBBS intern with irregular shifts. Very tidy, vegetarian, and absolutely no smoking. Love cooking Andhra food on weekends. Looking for a responsible flatmate.",
    compatibility: 91,
    budget: 12000,
    lifestyle: { smoking: false, drinking: false, pets: false, schedule: "flexible", cleanliness: "high" },
    preferences: ["Non-smoker", "Non-drinker", "Veg Kitchen", "Quiet Home"],
    preferredGender: "female",
    languages: ["Telugu", "Hindi", "English"],
    avatar: "https://img.freepik.com/premium-photo/young-smart-indian-businesswoman-smiling-face-standing-blur-background-modern-office-building-generative-ai-aig20_31965-140840.jpg",
    lookingIn: ["Banjara Hills", "HITEC City", "Jubilee Hills"],
    propertyId: "p18",
  },
  {
    id: "r4",
    name: "Rahul Gupta",
    age: 28,
    gender: "male",
    city: "Pune",
    occupation: "Product Manager",
    company: "Infosys BPM",
    bio: "Startup enthusiast and amateur photographer. I work from home 3 days a week and need solid Wi-Fi. Very sociable but respect quiet hours post 11 PM.",
    compatibility: 89,
    budget: 15000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "flexible", cleanliness: "medium" },
    preferences: ["Non-smoker", "Work from Home", "Fast Wi-Fi", "Weekend Socials"],
    preferredGender: "any",
    languages: ["Hindi", "English", "Marathi"],
    avatar: "https://img.freepik.com/premium-photo/portrait-indian-male-businessman-standing-white-background_875825-118793.jpg",
    lookingIn: ["Koregaon Park", "Viman Nagar", "Kalyani Nagar"],
  },
  {
    id: "r5",
    name: "Sneha Nair",
    age: 26,
    gender: "female",
    city: "Bangalore",
    occupation: "Data Scientist",
    company: "Zoho Corporation",
    bio: "South Indian, fond of filter coffee and classical Carnatic music. I am quiet during the week and host friends occasionally on weekends. Looking for like-minded women.",
    compatibility: 93,
    budget: 20000,
    lifestyle: { smoking: false, drinking: false, pets: true, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Non-drinker", "Pet Friendly", "Classical Music OK"],
    preferredGender: "female",
    languages: ["Malayalam", "Tamil", "English", "Hindi"],
    avatar: "https://plus.unsplash.com/premium_photo-1664478244612-d4b3238abd81?q=80&w=1170&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    lookingIn: ["Indiranagar", "Domlur", "CV Raman Nagar"],
    propertyId: "p10",
  },
  {
    id: "r6",
    name: "Aditya Singh",
    age: 26,
    gender: "male",
    city: "Hyderabad",
    occupation: "Full Stack Developer",
    company: "Wipro Technologies",
    bio: "Tech guy who codes late, sleeps at 2 AM, and wakes at 10. Loves biryani, cricket, and Playstation. Need a chill flatmate who doesn't mind my schedule.",
    compatibility: 86,
    budget: 16000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Night Owl", "Gaming Friendly", "Flexible Schedule"],
    preferredGender: "male",
    languages: ["Hindi", "English", "Bhojpuri"],
    avatar: "https://img.freepik.com/premium-photo/confident-indian-businessman-modern-office-environment-professional-profile-branding-corporate_91645-1355.jpg",
    lookingIn: ["HITEC City", "Gachibowli", "Kondapur"],
  },
  {
    id: "r7",
    name: "Ananya Krishnan",
    age: 23,
    gender: "female",
    city: "Bangalore",
    occupation: "MBA Student",
    company: "IIM Bangalore",
    bio: "First-year IIM student looking for accommodation near campus. Very studious during weekdays, but love exploring Bangalore's café scene on weekends.",
    compatibility: 88,
    budget: 14000,
    lifestyle: { smoking: false, drinking: false, pets: false, schedule: "flexible", cleanliness: "high" },
    preferences: ["Non-smoker", "Study-friendly", "Quiet Evenings", "Veg Preferred"],
    preferredGender: "female",
    languages: ["Tamil", "Kannada", "English", "Hindi"],
    avatar: "https://img.freepik.com/premium-photo/young-smart-indian-businesswoman-smiling-face-standing-blur-background-modern-office-building-generative-ai-aig20_31965-181605.jpg?w=740",
    lookingIn: ["Bannerghatta Road", "JP Nagar", "Jayanagar"],
  },
  {
    id: "r8",
    name: "Vikram Patel",
    age: 30,
    gender: "male",
    city: "Ahmedabad",
    occupation: "Chartered Accountant",
    company: "KPMG India",
    bio: "Finance professional and weekend cyclist. Strictly vegetarian, non-alcoholic. Very particular about a clean home. Love cooking Gujarati food and sharing it.",
    compatibility: 82,
    budget: 12000,
    lifestyle: { smoking: false, drinking: false, pets: false, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Non-drinker", "Veg Kitchen", "Vegetarian", "Clean Home"],
    preferredGender: "male",
    languages: ["Gujarati", "Hindi", "English"],
    avatar: "https://images.rawpixel.com/image_800/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDI0LTAxL3Jhd3BpeGVsX29mZmljZV8zMV9yZWFsaXN0aWNfcGhvdG9ncmFwaF9vZl9hX2luZGlhbl9tYW5pbmRpYW5fYV84NDlmODc5MS1jNmYxLTRhMTItOGMyOC0xMDIyNjQzNWNmNjRfMS5qcGc.jpg",
    lookingIn: ["Navrangpura", "Satellite", "Vastrapur"],
  },
  {
    id: "r9",
    name: "Deepika Iyer",
    age: 25,
    gender: "female",
    city: "Bangalore",
    occupation: "UX Designer",
    company: "Swiggy",
    bio: "UX designer obsessed with good design, street art, and craft beer. Work from Swiggy's Bangalore office 3 days a week. Looking for creative flatmates in vibrant areas.",
    compatibility: 95,
    budget: 22000,
    lifestyle: { smoking: false, drinking: true, pets: true, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Creative Types", "Pet Friendly", "Artsy Home"],
    preferredGender: "any",
    languages: ["Tamil", "Kannada", "English"],
    avatar: "https://img.freepik.com/premium-photo/young-smart-indian-businesswoman-smiling-face-standing-blur-background-creative-colorful-office-interior-design-generative-ai-aig20_31965-142318.jpg",
    lookingIn: ["Koramangala", "HSR Layout", "Indiranagar"],
    propertyId: "p3",
  },
  {
    id: "r10",
    name: "Rohit Kapoor",
    age: 27,
    gender: "male",
    city: "Delhi",
    occupation: "Marketing Manager",
    company: "Amazon India",
    bio: "Marketing manager who travels 10 days a month. Keep my room clean, pay rent on time, value privacy and respect. Looking for a professional flatmate in South Delhi.",
    compatibility: 90,
    budget: 20000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Professional", "Privacy Valued", "Clean Common Areas"],
    preferredGender: "any",
    languages: ["Hindi", "English", "Punjabi"],
    avatar: "https://img.freepik.com/premium-photo/professional-indian-businessman-formal-suit-with-arms-crossed-confident-smiling-ideal-corporate-design-marketing-materials_91645-7242.jpg",
    lookingIn: ["Greater Kailash", "Lajpat Nagar", "South Extension"],
    propertyId: "p13",
  },
  {
    id: "r11",
    name: "Pooja Verma",
    age: 24,
    gender: "female",
    city: "Mumbai",
    occupation: "Fashion Designer",
    company: "Fab India",
    bio: "Textile designer who fills the home with fabric swatches and good music. Vegan, eco-conscious, and love indoor plants. Need a like-minded creative woman co-tenant.",
    compatibility: 87,
    budget: 18000,
    lifestyle: { smoking: false, drinking: false, pets: true, schedule: "flexible", cleanliness: "medium" },
    preferences: ["Non-smoker", "Vegan Kitchen", "Plants OK", "Creative", "Eco-friendly"],
    preferredGender: "female",
    languages: ["Hindi", "English"],
    avatar: "https://img.freepik.com/premium-photo/young-indian-businesswoman-employee-standing-white-background_1254992-279705.jpg",
    lookingIn: ["Bandra West", "Juhu", "Khar"],
  },
  {
    id: "r12",
    name: "Kiran Rao",
    age: 26,
    gender: "male",
    city: "Hyderabad",
    occupation: "AI Researcher",
    company: "CDAC Hyderabad",
    bio: "Deep into machine learning and philosophy. Introverted but friendly. I cook occasionally and keep shared spaces clean. Need fast internet and a quiet environment.",
    compatibility: 84,
    budget: 14000,
    lifestyle: { smoking: false, drinking: false, pets: false, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Non-drinker", "Fast Wi-Fi", "Quiet Home", "Bookish"],
    preferredGender: "any",
    languages: ["Kannada", "Telugu", "English", "Hindi"],
    avatar: "https://static.vecteezy.com/system/resources/previews/048/817/564/non_2x/confident-young-professional-standing-in-urban-street-during-bright-daylight-photo.jpeg",
    lookingIn: ["HITEC City", "Madhapur", "Gachibowli"],
    propertyId: "p18",
  },
  {
    id: "r13",
    name: "Meera Pillai",
    age: 28,
    gender: "female",
    city: "Chennai",
    occupation: "Senior Journalist",
    company: "The Hindu",
    bio: "Journalist with irregular hours (morning deadlines!). Love cooking Kerala food, reading, and Tamil cinema. Non-vegetarian, but respect all dietary preferences.",
    compatibility: 85,
    budget: 15000,
    lifestyle: { smoking: false, drinking: false, pets: true, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Pet Friendly", "Tidy Home", "Independent"],
    preferredGender: "female",
    languages: ["Malayalam", "Tamil", "English"],
    avatar: "https://img.freepik.com/premium-photo/photo-confident-indian-businesswoman-standing-with-her-arms-crossed-smiling_1025753-136174.jpg",
    lookingIn: ["Adyar", "Besant Nagar", "Thiruvanmiyur"],
    propertyId: "p15",
  },
  {
    id: "r14",
    name: "Siddharth Joshi",
    age: 25,
    gender: "male",
    city: "Pune",
    occupation: "Startup Founder",
    company: "Self-employed (SaaS)",
    bio: "Running a bootstrapped SaaS startup from home. Spend most of my day on calls. Need great Wi-Fi, quiet co-tenants, and an ergonomic-friendly flat. No drama.",
    compatibility: 88,
    budget: 18000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "flexible", cleanliness: "medium" },
    preferences: ["Non-smoker", "Work from Home", "Fast Wi-Fi", "Low Noise"],
    preferredGender: "any",
    languages: ["Marathi", "Hindi", "English"],
    avatar: "https://tse1.mm.bing.net/th/id/OIP.Vb_Obw2n1XePve8FobwaYgHaE7?cb=thfc1&w=626&h=417&rs=1&pid=ImgDetMain&o=7&rm=3",
    lookingIn: ["Koregaon Park", "Baner", "Aundh"],
  },
  {
    id: "r15",
    name: "Divya Agarwal",
    age: 23,
    gender: "female",
    city: "Delhi",
    occupation: "UPSC Aspirant",
    company: "Self-study",
    bio: "Full-time UPSC prep. I study 12 hours daily and need absolute quiet. Very clean, vegetarian, no smoking or drinking. Looking for a disciplined female co-tenant.",
    compatibility: 81,
    budget: 9000,
    lifestyle: { smoking: false, drinking: false, pets: false, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Non-drinker", "Vegetarian", "Silent Study Zone", "Female Only"],
    preferredGender: "female",
    languages: ["Hindi", "English"],
    avatar: "https://img.freepik.com/premium-photo/closeup-happy-pretty-indian-business-womancloseup-happy-pretty-indian-business-woman_1108314-121888.jpg",
    lookingIn: ["Mukherjee Nagar", "Karol Bagh", "Old Rajendra Nagar"],
  },
  {
    id: "r16",
    name: "Aryan Khanna",
    age: 26,
    gender: "male",
    city: "Noida",
    occupation: "Game Developer",
    company: "Ubisoft India",
    bio: "AAA game developer who sleeps late and plays guitar badly. My desk is chaotic but shared spaces are clean. Love cooking and feeding everyone. Very sociable.",
    compatibility: 83,
    budget: 16000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Night Owl", "Gaming Friendly", "Sociable"],
    preferredGender: "any",
    languages: ["Hindi", "English"],
    avatar: "https://tse3.mm.bing.net/th/id/OIP.6v8YXyzJAfxWzejsXQ0sbwHaE7?cb=thfc1&w=626&h=417&rs=1&pid=ImgDetMain&o=7&rm=3",
    lookingIn: ["Sector 62", "Sector 18", "Sector 50"],
  },
  {
    id: "r17",
    name: "Shreya Bose",
    age: 27,
    gender: "female",
    city: "Kolkata",
    occupation: "Architect",
    company: "Hafeez Contractor Studio",
    bio: "Architect who draws at midnight and drinks too much chai. Love classical Hindustani music, detective fiction, and Kolkata's Sunday morning book market.",
    compatibility: 92,
    budget: 12000,
    lifestyle: { smoking: false, drinking: false, pets: true, schedule: "night_owl", cleanliness: "medium" },
    preferences: ["Non-smoker", "Pet Friendly", "Artsy Home", "Books OK"],
    preferredGender: "female",
    languages: ["Bengali", "Hindi", "English"],
    avatar: "https://img.freepik.com/premium-photo/confident-young-indian-businesswoman-office-smiling-business-theme-portrait-shot-plain-office-background-office-smiling_936686-22520.jpg",
    lookingIn: ["Salt Lake", "Park Street", "Alipore"],
    propertyId: "p17",
  },
  {
    id: "r18",
    name: "Tanmay Dey",
    age: 24,
    gender: "male",
    city: "Bangalore",
    occupation: "DevOps Engineer",
    company: "Google India",
    bio: "Googler who works hard and plays harder. Love trekking the Sahyadris on weekends. Non-smoker, occasional beer at home. Very punctual with rent and bills.",
    compatibility: 97,
    budget: 25000,
    lifestyle: { smoking: false, drinking: true, pets: false, schedule: "early_bird", cleanliness: "high" },
    preferences: ["Non-smoker", "Fitness Oriented", "Outdoors", "Punctual"],
    preferredGender: "any",
    languages: ["Bengali", "Hindi", "English", "Kannada"],
    avatar: "https://tse3.mm.bing.net/th/id/OIP.bQDR_9X8UH520jrlslKhoQHaE7?cb=thfc1&w=740&h=493&rs=1&pid=ImgDetMain&o=7&rm=3",
    lookingIn: ["Whitefield", "Marathahalli", "Bellandur"],
    propertyId: "p1",
  },
];

// ─── Mock chat threads ────────────────────────────────────────────────────────

export type ChatContact = {
  id: string;
  name: string;
  avatar: string;
  lastMessage: string;
  time: string;
  unread: number;
  online: boolean;
  context: string; // what they're discussing
};

export type ChatMessage = {
  sender: "me" | "other";
  text: string;
  time: string;
};

export const CHAT_CONTACTS: ChatContact[] = [
  { id: "c1", name: "Priya Sharma", avatar: "https://img.freepik.com/premium-photo/young-smart-indian-businesswoman-smiling-face-standing-blur-background-modern-office-building-generative-ai-aig20_31965-130044.jpg", lastMessage: "Yes, Koramangala works perfectly!", time: "2m", unread: 2, online: true, context: "Flat in Koramangala" },
  { id: "c2", name: "Arjun Mehta", avatar: "https://img.freepik.com/premium-photo/young-smart-indian-businessman-smiling-face-standing-blur-background-busy-office-generative-ai-aig20_31965-142159.jpg", lastMessage: "Can we schedule a visit this Sunday?", time: "1h", unread: 0, online: false, context: "Andheri flat inquiry" },
  { id: "c3", name: "Narayana Swamy", avatar: "https://tse2.mm.bing.net/th/id/OIP._rEusoWjUtIDuL3CEMFayAHaE7?cb=thfc1&w=626&h=417&rs=1&pid=ImgDetMain&o=7&rm=3", lastMessage: "Maintenance is covered in rent.", time: "3h", unread: 1, online: true, context: "Whitefield studio" },
  { id: "c4", name: "Kavya Reddy", avatar: "https://img.freepik.com/premium-photo/young-smart-indian-businesswoman-smiling-face-standing-blur-background-modern-office-building-generative-ai-aig20_31965-140840.jpg", lastMessage: "I'm okay with the deposit amount.", time: "Yesterday", unread: 0, online: false, context: "HITEC City room" },
  { id: "c5", name: "Ramesh Kapoor", avatar: "https://img.freepik.com/premium-photo/man-suit-stands-front-window_662214-545818.jpg", lastMessage: "Lease is ready to be signed.", time: "Yesterday", unread: 0, online: false, context: "Lajpat Nagar flat" },
];

export const MOCK_THREADS: Record<string, ChatMessage[]> = {
  c1: [
    { sender: "other", text: "Hi! I saw your listing on Homigo for the 3BHK in Koramangala. Is the private room still available?", time: "10:02 AM" },
    { sender: "me", text: "Yes, it's available! The room is 14×12 ft with a built-in wardrobe and a dedicated work desk.", time: "10:05 AM" },
    { sender: "other", text: "Perfect. I'm a software engineer at TCS. I work standard hours and keep my space very clean. I prefer a non-smoking household.", time: "10:07 AM" },
    { sender: "me", text: "That matches our house rules exactly. No smoking, no parties on weekdays. We have two other flatmates — a designer and a data analyst.", time: "10:10 AM" },
    { sender: "other", text: "Sounds ideal. The rent is ₹25,000 right? Does that include maintenance and internet?", time: "10:12 AM" },
    { sender: "me", text: "Yes, ₹25,000 all-inclusive. 300 Mbps Wi-Fi, society maintenance, and housekeeping twice a week.", time: "10:14 AM" },
    { sender: "other", text: "Yes, Koramangala works perfectly!", time: "10:16 AM" },
  ],
  c2: [
    { sender: "other", text: "Hello! I'm interested in the 2BHK listing in Andheri West. I'm looking to move in by mid-April.", time: "9:00 AM" },
    { sender: "me", text: "Great! The flat is available from April 15. It's fully furnished with a modular kitchen and two ACs.", time: "9:15 AM" },
    { sender: "other", text: "That works. What's the security deposit? And is the building pet-free?", time: "9:20 AM" },
    { sender: "me", text: "Security deposit is 2 months (₹90,000). No pets allowed, sorry — building society rules.", time: "9:30 AM" },
    { sender: "other", text: "Understood. No pets is fine. Can we schedule a visit this Sunday?", time: "9:45 AM" },
  ],
  c3: [
    { sender: "other", text: "I am Narayana Swamy, the owner of the Whitefield studio. Thank you for your inquiry.", time: "2:00 PM" },
    { sender: "me", text: "Hi! Yes, I'm interested. Is the studio fully furnished?", time: "2:05 PM" },
    { sender: "other", text: "Yes, fully furnished with a queen bed, wardrobe, study table, and a modular kitchen. AC included.", time: "2:10 PM" },
    { sender: "me", text: "Great. What about maintenance and society charges?", time: "2:12 PM" },
    { sender: "other", text: "Maintenance is covered in rent. Society charges of ₹1,500/month are extra.", time: "2:15 PM" },
  ],
  c4: [
    { sender: "other", text: "Hi, I'm Kavya. I'm an MBBS intern at Yashoda Hospital. I'm interested in the room in HITEC City.", time: "11:00 AM" },
    { sender: "me", text: "Welcome Kavya! The room is in a women-only flat of three. Very safe area, 24/7 security in the building.", time: "11:10 AM" },
    { sender: "other", text: "That's reassuring. Is there a curfew? I sometimes have night shifts.", time: "11:15 AM" },
    { sender: "me", text: "No curfew at all. We all have professional lives so we understand irregular hours.", time: "11:20 AM" },
    { sender: "other", text: "I'm okay with the deposit amount.", time: "11:25 AM" },
  ],
  c5: [
    { sender: "other", text: "Namaste, I'm Ramesh Kapoor. I see you've applied for the Lajpat Nagar flat.", time: "4:00 PM" },
    { sender: "me", text: "Yes! I'm very interested. I've been looking in South Delhi for a while.", time: "4:05 PM" },
    { sender: "other", text: "Your profile looks good. Can you share your last 3 months' pay slips and employment letter?", time: "4:10 PM" },
    { sender: "me", text: "Of course, I'll send them right away on email.", time: "4:12 PM" },
    { sender: "other", text: "Lease is ready to be signed.", time: "4:30 PM" },
  ],
};